version: "3.3"

services:
    client:
        image: nginx
        ports:
            - 80:80
        volumes:
            - ./src:/usr/share/nginx/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        logging:
            driver: "fluentd"
            options:
              fluentd-address: localhost:24224
              tag: "nginx.access"
        depends_on: 
            - "fluentd" 
        networks:
            - bridge

    fluentd:
        image: sarikajoshi/fluentd-mongodb-plugin
        ports:
            - "24224:24224"
        depends_on:  
            - "backend"
        volumes:
            - ./fluentd/etc:/fluentd/etc
        networks:
            - bridge

    backend:
        image: mongo
        ports:
            - "3100:27017"
        networks:
            - bridge

networks:
  bridge:
